baseURL: 'https://example.com'
languageCode: en-us
title: Cactus 2 Demo Site
theme: cactus-2
copyright: You
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writings
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: dracula
    tabWidth: 4
params:
  colortheme: white
  rss: true
  googleAnalyticsAsync: true
  showAllPostsArchive: false
  description: >-
    Hugo is a general-purpose website framework. Technically speaking, Hugo is a
    static site generator. Unlike systems that dynamically build a page with
    each visitor request, Hugo builds pages when you create or update your
    content. Since websites are viewed far more often than they are edited, Hugo
    is designed to provide an optimal viewing experience for your website’s end
    users and an ideal writing experience for website authors.
  mainSection: posts
  showAllPostsOnHomePage: false
  postsOnHomePage: 5
  tagsOverview: true
  showProjectsList: true
  projectsUrl: 'https://github.com/gohugoio'
  dateFormat: '2006-01-02'
  show_updated: true
  showReadTime: true
  comments:
    enabled: true
    engine: cactus_comments
    utterances:
      repo: <github_username>/<github_reponame>
      label: hugo-site-name
      theme: github-light
    cactuscomments:
      siteName: your_cactus_comments_sitename
  social:
    - name: github
      link: 'https://github.com/gohugoio'
    - name: linkedin
      link: 'https://www.linkedin.com/company/github/'
    - name: email
      link: example@example.com
